# Generated by Django 5.0.2 on 2024-03-01 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepstyleapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='color',
            field=models.CharField(choices=[('Red', 'Red'), ('Green', 'Green'), ('Blue', 'Blue'), ('Purple', 'Purple'), ('Black', 'Black')], default='Black', max_length=20),
        ),
    ]
