# Generated by Django 5.0.2 on 2024-03-01 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepstyleapp', '0002_shoe_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='color',
            field=models.CharField(choices=[('Red', 'Red'), ('Green', 'Green'), ('Blue', 'Blue'), ('Purple', 'Purple'), ('Black', 'Black'), ('White', 'White')], default='Black', max_length=20),
        ),
    ]
