# Generated by Django 5.0.2 on 2024-03-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepstyleapp', '0003_alter_shoe_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('India', 'India'), ('Algeria', 'Algeria'), ('Afghanistan', 'Afghanistan'), ('Ghana', 'Ghana'), ('Albania', 'Albania'), ('Bahrain', 'Bahrain'), ('Colombia', 'Colombia'), ('Dominican Republic', 'Dominican Republic'), ('Bangladesh', 'Bangladesh')], default='India', max_length=100)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('address2', models.CharField(blank=True, max_length=100, null=True)),
                ('state_country', models.CharField(max_length=100)),
                ('postal_zip', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('on', models.CharField(max_length=255)),
            ],
        ),
    ]
